services:
  # Backend API
  - type: web
    name: internship-backend
    env: node
    rootDir: webinter/server
    buildCommand: npm install
    startCommand: node index.js
    
  # Frontend Static Site
  - type: web
    name: internship-frontend
    env: static
    rootDir: webinter/client
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
